### ISSUE TITLE
Could you provide the requirement?

### ISSUE THREAD

**Issue by jintianchen** [acrarshin/RPNet#2]
It's impressive work, but i am confused about the requirement of enviroment. Could you provide the requirement?

**Comment by acrarshin** [comment]
I have added a requirement.txt file. Excuse the delay

**Comment by jintianchen** [comment]
thank u,and i want to know if training code is provide, i am really interested in your novel worok

**Comment by jintianchen** [comment]
thank u,and i want to know if training code is provide, i am really interested in your novel work.

**Comment by acrarshin** [comment]
A jupyter notebook with the training code was released. Hope it helps.

**Comment by eladwass** [comment]
Can we use the obtain_data function in utils.py when training? I saw a lot of data preparations in the ipynb.
