### ISSUE TITLE
Module Not Found Error

### ISSUE THREAD

**Issue by ckbharti** [acrarshin/RPNet#3]
I am getting the following error
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-7-06ed73fd8350> in <module>()
     31 
     32 ### Importing Custom Libraries
---> 33 from network import IncUNet

ModuleNotFoundError: No module named 'network'
<img width="589" alt="RPnet" src="https://user-images.githubusercontent.com/46262437/118397956-12a1fe80-b674-11eb-80b2-dd398a6d04d5.png">

**Comment by lcaronson** [comment]
For those who are stuck on this, you need to download the whole GitHub repo and run the code in order to avoid the error.

**Comment by acrarshin** [comment]
@ckbharti I somehow missed this issue. 

@lcaronson is absolutely right, We need to import the IncUNet classs from the network.py module.
